# Generated by Django 5.0.7 on 2024-08-05 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('duedate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('msub', 'Submit Bull'), ('fsub', 'Submit Cow'), ('breed', 'Breed')], max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('traitset', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
                ('classcode', models.CharField(max_length=255)),
                ('trait_visibility', models.JSONField()),
                ('recessive_visibility', models.JSONField()),
                ('trend_log', models.JSONField(default=dict)),
                ('enrollment_tokens', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectedclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.assignment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Herd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('breedings', models.IntegerField(default=0)),
                ('connected_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.class')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='herd_enrollment', to='base.enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='herd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_herd', to='base.herd'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_herd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_class_herd', to='base.herd'),
        ),
        migrations.AddField(
            model_name='class',
            name='starter_herd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_starter_herd', to='base.herd'),
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generation', models.IntegerField(default=0)),
                ('male', models.BooleanField()),
                ('genotype', models.JSONField(default=dict)),
                ('phenotype', models.JSONField(default=dict)),
                ('recessives', models.JSONField(default=dict)),
                ('pedigree', models.JSONField(blank=True, null=True)),
                ('inbreeding', models.FloatField(blank=True, null=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_dam', to='base.animal')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_sire', to='base.animal')),
                ('connectedclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.class')),
                ('herd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.herd')),
            ],
        ),
    ]
