# Generated by Django 5.0.7 on 2024-08-07 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='genotype',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='phenotype',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='recessives',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_herd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_class_herd', to='base.herd'),
        ),
        migrations.AlterField(
            model_name='class',
            name='starter_herd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_starter_herd', to='base.herd'),
        ),
        migrations.AlterField(
            model_name='herd',
            name='connected_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.class'),
        ),
    ]
