# Generated by Django 5.0.7 on 2024-08-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_animal_genotype_alter_animal_phenotype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herd',
            old_name='connected_class',
            new_name='connectedclass',
        ),
    ]
