# Generated by Django 5.0.7 on 2024-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_animal_inbreeding_alter_animal_pedigree'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='Untitled Assignment', max_length=255),
            preserve_default=False,
        ),
    ]
