# Generated by Django 5.0.7 on 2024-08-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_assignment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='allow_other_animals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='class',
            name='default_animal',
            field=models.CharField(default='Dog', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='animal',
            field=models.CharField(default='Dog', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
