# Generated by Django 5.0.7 on 2024-08-11 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_enrollment_confirmed_enrollmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='connectedclass',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='base.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentstep',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.assignment'),
            preserve_default=False,
        ),
    ]
