# Generated by Django 5.0.7 on 2024-08-23 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_assignment_connectedclass_assignmentstep_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='herd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.herd'),
        ),
        migrations.AlterField(
            model_name='assignmentstep',
            name='step',
            field=models.CharField(choices=[('msub', 'Submit Male'), ('fsub', 'Submit Female'), ('breed', 'Breed')], max_length=255),
        ),
    ]
