# Generated by Django 5.0.7 on 2024-08-23 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_animal_herd_alter_assignmentstep_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentstep',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentstep_assignment', to='base.assignment'),
        ),
        migrations.AlterField(
            model_name='class',
            name='trend_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
