# Generated by Django 5.0.7 on 2025-01-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_class_net_merit_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='genomic_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='ptas',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
