# Generated by Django 5.0.7 on 2025-01-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_animal_genomic_tests_animal_ptas_alter_class_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='hide_female_pta',
            field=models.BooleanField(default=False),
        ),
    ]
