# Generated by Django 5.0.7 on 2025-01-02 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_class_hide_female_pta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='starter_herd',
        ),
    ]
