# Generated by Django 5.0.7 on 2025-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_class_quarantine_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
