# Generated by Django 5.0.7 on 2025-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_class_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='assignment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
