# Generated by Django 5.0.7 on 2025-08-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_animal_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='enrollment_tokens',
            field=models.IntegerField(default=10),
        ),
    ]
