# Generated by Django 5.0.7 on 2025-08-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_class_enrollment_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='allow_herd_rename',
            field=models.BooleanField(default=True),
        ),
    ]
